export enum CuisineType {
    American = 'american',
    Asian = 'asian',
    British = 'british',
    Caribbean = 'caribbean',
    CentralEurope = 'central europe',
    Chinese = 'chinese',
    EasternEurope = 'eastern europe',
    French = 'french',
    Greek = 'greek',
    Indian = 'indian',
    Italian = 'italian',
    Japanese = 'japanese',
    Korean = 'korean',
    Kosher = 'kosher',
    Mediterranean = 'mediterranean',
    Mexican = 'mexican',
    MiddleEastern = 'middle eastern',
    Nordic = 'nordic',
    SouthAmerican = 'south american',
    SouthEastAsian = 'south east asian',
    World = 'world'
}

export enum CuisineTypeNames{
    American = 'American',
    Asian = 'Asian',
    British = 'British',
    Caribbean = 'Caribbean',
    CentralEurope = 'Central Europe',
    Chinese = 'Chinese',
    EasternEurope = 'Eastern Europe',
    French = 'French',
    Greek = 'Greek',
    Indian = 'Indian',
    Italian = 'Italian',
    Japanese = 'Japanese',
    Korean = 'Korean',
    Kosher = 'Kosher',
    Mediterranean = 'Mediterranean',
    Mexican = 'Mexican',
    MiddleEastern = 'Middle Eastern',
    Nordic = 'Nordic',
    SouthAmerican = 'South American',
    SouthEastAsian = 'South East Asian',
    World = 'World'
}