export enum DishType {
    AlcoholCocktail = 'alcohol cocktail',
    BiscuitsAndCookies = 'biscuits and cookies',
    Bread = 'bread',
    Cereals = 'cereals',
    CondimentsAndSauces = 'condiments and sauces',
    Desserts = 'desserts',
    Drinks = 'drinks',
    Egg = 'egg',
    IceCreamAndCustard = 'ice cream and custard',
    MainCourse = 'main course',
    Pancake = 'pancake',
    Pasta = 'pasta',
    Pastry = 'pastry',
    PiesAndTarts = 'pies and tarts',
    Pizza = 'pizza',
    Preps = 'preps',
    Preserve = 'preserve',
    Salad = 'salad',
    Sandwiches = 'sandwiches',
    Seafood = 'seafood',
    SideDish = 'side dish',
    Soup = 'soup',
    SpecialOccasions = 'special occasions',
    Starter = 'starter',
    Sweets = 'sweets'
}